apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: default
data:
  POSTGRES_DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/eprc"
  TEST_POSTGRES_DATABASE_URL: "postgresql+psycopg2://postgres:postgres-service@postgres/eprc_test"
  FLASK_ENV: "production"
  HOST: "127.0.0.1"
  SECRET: "kjdudfnsakfkj3rjkekf813rkniusadf3" 