version: "3.7"
services:
    api:
        build: .
        image: bisonlou/eprc-portal-api
        container_name: api
        env_file: .env
        ports:
            - "8080:8080"
        depends_on:
            - "db" 
        restart: on-failure
        healthcheck:
            test: "curl localhost:8080/health || exit 1"
            interval: 10s
            timeout: 2s
            retries: 5
            start_period: 15s

    web:
        image: web:latest
        container_name: web
        ports:
            - "3000:3000"
        depends_on:
            - "api"
            - "db"
        restart: on-failure
                    
    db:
        image: postgres:latest
        env_file: .db_env
        container_name: postgres
        ports: 
            - "5432:5432"
        volumes:
            - /postgres-data:/var/lib/postgresql/data


   