"""empty message

Revision ID: 72dcfdcbe74d
Revises: 662c35ace21a
Create Date: 2020-02-14 14:59:43.943125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dcfdcbe74d'
down_revision = '662c35ace21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationery_requisition_details', sa.Column('requisition_id', sa.Integer(), nullable=True))
    op.drop_constraint('stationery_requisition_details_order_id_fkey', 'stationery_requisition_details', type_='foreignkey')
    op.create_foreign_key(None, 'stationery_requisition_details', 'stationery_requisitions', ['requisition_id'], ['id'])
    op.drop_column('stationery_requisition_details', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationery_requisition_details', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stationery_requisition_details', type_='foreignkey')
    op.create_foreign_key('stationery_requisition_details_order_id_fkey', 'stationery_requisition_details', 'stationery_requisitions', ['order_id'], ['id'])
    op.drop_column('stationery_requisition_details', 'requisition_id')
    # ### end Alembic commands ###
