"""empty message

Revision ID: 77d60eb5d875
Revises: b0a8ff799b15
Create Date: 2020-02-14 12:37:55.201682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d60eb5d875'
down_revision = 'b0a8ff799b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stationery', ['name'])
    op.add_column('stationery_requisition_details', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('stationery_requisition_details_item_fkey', 'stationery_requisition_details', type_='foreignkey')
    op.create_foreign_key(None, 'stationery_requisition_details', 'stationery', ['item_id'], ['id'])
    op.drop_column('stationery_requisition_details', 'item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationery_requisition_details', sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stationery_requisition_details', type_='foreignkey')
    op.create_foreign_key('stationery_requisition_details_item_fkey', 'stationery_requisition_details', 'stationery', ['item'], ['id'])
    op.drop_column('stationery_requisition_details', 'item_id')
    op.drop_constraint(None, 'stationery', type_='unique')
    # ### end Alembic commands ###
