"""empty message

Revision ID: 8f610692d38c
Revises: fbfad1293bbb
Create Date: 2020-03-06 10:22:20.215619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f610692d38c'
down_revision = 'fbfad1293bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'remarks')
    # ### end Alembic commands ###
