"""empty message

Revision ID: fbfad1293bbb
Revises: a009678b7bd3
Create Date: 2020-03-05 15:46:08.429424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfad1293bbb'
down_revision = 'a009678b7bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('consultant_months', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('project_description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('service_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'service_description')
    op.drop_column('projects', 'project_description')
    op.drop_column('projects', 'consultant_months')
    # ### end Alembic commands ###
